image:
- Visual Studio 2017
- Visual Studio 2019

platform:
- x86
- x64

environment:
    VCVAR17: 'C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat'
    VCVAR17_x86: \C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars32.bat'
    VCVAR19: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat'
    VCVAR19_x86: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars32.bat'

before_build:
- python -m pip install --user scons

build_script:
 - scons
