language: c++

os:
  - linux

matrix:
  include: 
    - dist: bionic
      compiler:
        - gcc
        - clang
    - dist: focal
      compiler:
        - gcc
        - clang
    - dist: jammy
      compiler:
      - gcc
      - clang

before_install:
  - sudo apt-get install -y scons
  - wget http://iausofa.org/2021_0512_C/sofa_c-20210512.tar.Z
  - tar -xzvf sofa_c-20210512.tar.Z
  - cd sofa/20210512/c/src
  - sed -i 's/\/home\/travis/\/usr\/local/g' makefile
  - make
  - sed -i 's/\/home\/travis/\/usr\/local/g' makefile
  - sudo make install
  - sudo cp sofa.h sofam.h /usr/local/include
  - sudo cp libsofa_c.a /usr/local/lib
  - cd ../../../../
  - sudo ldconfig

script:
 - sudo scons install
 #- scons --make-check
 #- cd var && bash make_unit_tests.sh
