language: c++
dist: bionic
compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get install -y scons
  - wget http://iausofa.org/2021_0512_C/sofa_c-20210512.tar.Z
  - tar -xzvf sofa_c-20210512.tar.Z
  - cd sofa/20210512/c/src
  - sed -i 's/\/home\/travis/\/usr\/local/g' makefile
  - make
  - sudo make install
  - cd ../../../../
  - sudo ldconfig

script:
 - sudo scons install
 - scons --make-check
 - cd var && bash make_unit_tests.sh
