name: Linux CI build

on:
  push:
    branches: [ "master", "cleanup" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install scons
      run: sudo apt-get install -y scons

    - name: install (latest) eigen
      run: sudo apt install libeigen3-dev
    
    - name: build (production), gcc
      run: scons
    
    - name: build (production, c++20), gcc
      run: scons --std=20
    
    - name: build (debug), gcc
      run: scons debug=1
    
    - name: build (debug & tests), gcc
      run: scons debug=1 test=1
    
    - name: build (production), clang
      run: scons --cxx=clang++
    
    - name: build (debug & tests), clang
      run: scons debug=1 test=1 --cxx=clang++
    
    - name: build (production, C++20), clang
      run: scons --cxx=clang++ --std=20
