name: CI test

# Only trigger, when the build workflow succeeded
on:
  workflow_run:
    workflows: ["Linux CI build"]
    types:
      - completed

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install scons
      run: sudo apt-get install -y scons

    - name: install (latest) eigen
      run: sudo apt install libeigen3-dev
    
    - name: build (tests), gcc
      run: scons test=1
    
    - name: Run test suites
      run: python3 run_test_suite.py --progs-dir=test
